CREATE DATABASE STUDY; -- CREAZIONE DB
USE STUDY;

-- CREAZIONE TABELLA REGIONI
CREATE TABLE region (
COUNTRY VARCHAR(20) NOT NULL,
DESCRIPTION VARCHAR(45) NOT NULL,
NUM_REGION INT NOT NULL,
PRIMARY KEY (COUNTRY));
  
 
-- CREAZIONE TABELLA PRODOTTI
CREATE TABLE product (
IDPRODUCT INT NOT NULL AUTO_INCREMENT,
PRODUCT_NAME VARCHAR(45) NOT NULL,
KG DECIMAL(3),
PRICE DECIMAL(2),
PRIMARY KEY (IDPRODUCT));
  
-- AGGIUNGO LA CATEGORIA ALLA TABELLA PRODUCT
ALTER TABLE product
ADD COLUMN CATEGORY_PRODUCT VARCHAR(25) NOT NULL;
  
-- CREAZIONE TABELLA VENDITA CON CHIAVI SECONDARIE LE CHIAVI PRIMARIE DELLE ALTRE 2 TABELLE

CREATE TABLE sales (
  IDSALES INT NOT NULL AUTO_INCREMENT UNIQUE,
  SELLER_NAME VARCHAR(45) NULL,
  QUANTITY VARCHAR(45) NULL,
  IDPRODUCT INT,
  COUNTRY VARCHAR(20),
PRIMARY KEY (IDSALES),
CONSTRAINT IDPRODUCT
FOREIGN KEY (IDPRODUCT)
REFERENCES study.product (IDPRODUCT),
CONSTRAINT COUNTRY
FOREIGN KEY (COUNTRY)
REFERENCES study.region (COUNTRY));
    
  SELECT * FROM REGION;
   SELECT * FROM SALES;
    SELECT * FROM PRODUCT;
    

